---
title: "Multi-label cost-constrained feature selection"
output: html_notebook
---

Load all necessary user-defined functions.
```{r echo = T, results = 'hide'}
source("./src/utils.R")
source("./src/selectors.R")
```

Load all external libraries.
```{r echo = T, results = 'hide'}
library(jsonlite)
library(progress)
library(lubridate)
library(utiml)
library(dplyr)
library(hash)
library(log4r)
library(mldr.datasets)
```

Set global parameters.
```{r}
SEED = 0
BUDGET = 20
```

Load example dataset.
```{r}
data = flags$dataset
X_all = data %>% select(1:19) %>% mutate_if(is.character, as.factor)
Y_all = data %>% select(20:26) %>% mutate_if(is.character, as.factor)

data_splited = train_test_split(X_all, Y_all, test_size = 0.1, seed=SEED)
X_train = data_splited$X_train
Y_train = data_splited$Y_train
X_test = data_splited$X_test
Y_test = data_splited$Y_test

costs = c(
  1,1,1,
  2,2,2,
  3,3,3,
  4,4,4,
  5,5,5,
  6,6,6,
  7
)
```

Create mutli-label dataset in mldr library API.
```{r}
target_idx = ncol(X_train) + seq(1, ncol(Y_train))
mldr_dataset_train = mldr_from_dataframe(cbind(X_train, Y_train), target_idx)
mldr_dataset_test = mldr_from_dataframe(cbind(X_test, Y_test), target_idx)
```

Run selected feature selection algorithms.
```{r}
selection_STFS = STFS(X_train, Y_train, costs, BUDGET)
selection_DCRMFS = DCRMFS(X_train, Y_train, costs, BUDGET)
selection_AMI = AMI(X_train, Y_train, costs, BUDGET)
selection_SCLS = SCLS(X_train, Y_train, costs, BUDGET)
selection_MDMR = MDMR(X_train, Y_train, costs, BUDGET)
selection_MVML = MVML(X_train, Y_train, costs, BUDGET)

l_opt = lambda_optimal(X_train, Y_train, costs, BUDGET, l_cnt=5, l_max=NULL)
selection_PROPOSED_CRITERION = PROPOSED_CRITERION(X_train, Y_train, costs, BUDGET, l_opt)
```

Choose one feature selection algorithm result.
```{r}
selected_features = selection_PROPOSED_CRITERION$selection
```

Evaluate the results with selected model.
```{r}
mldr_dataset_train_subset = create_subset(mldr_dataset_train, cols = selected_features)
mldr_dataset_test_subset = create_subset(mldr_dataset_test, cols = selected_features)

model <- br(mldr_dataset_train_subset, 'KNN', k=10)
preds <- predict(model, mldr_dataset_test_subset)
multilabel_evaluate(mldr_dataset_test_subset, preds)
```
